platform :ios, '14.1.99'

target 'Runner' do
  use_frameworks!

  pod "Firebase/Analytics"
  pod "Firebase/Crashlytics"

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if Gem::Version.new('14.1.99') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.1.99'
        end
      end
    end
  end

end
