name: aiko_bot
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  google_fonts: ^0.3.9
  path_provider: ^1.6.24
  google_sign_in: ^4.5.5
  cupertino_icons: ^1.0.0
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  firebase_analytics: ^6.0.2
  flutter_smart_reply: ^0.0.1
  firebase_crashlytics: ^0.2.2
  flutter_auth_buttons: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets: 
    - lib/images/koala.png
    - lib/images/koala2.png
